import Link from 'next/link';
import type {Metadata} from 'next';
import {CopyCommand} from '../copy-command';
import {repository,sourceInstall} from '../config';
export const metadata:Metadata={title:'Getting started — perfratio',description:'Install perfratio, run benchmarks, understand output, measure energy and export reports.'};
export default function Docs(){return <><header className="header"><div className="container header-inner"><Link className="brand" href="/">perfratio<span className="brand-note">DOCS</span></Link><div className="header-actions"><Link href="/">Home</Link><a href={repository}>GitHub ↗</a></div></div></header><main className="container docs"><p className="eyebrow">GETTING STARTED</p><h1>A better benchmark,<br/><span className="accent">one command at a time.</span></h1><p>perfratio is a Rust command-line benchmarking tool descended from joulex and hyperfine. Compare arbitrary shell commands with timing, peak memory, optional energy telemetry and statistical analysis.</p><nav className="docs-nav" aria-label="Guide sections"><a href="#install">Installation</a><a href="#first-run">First benchmark</a><a href="#output">Read the output</a><a href="#energy">Energy</a><a href="#export">Exports</a></nav>
<section id="install"><h2>Install from source</h2><p>Install Rust 1.88 or newer with <a className="text-link" href="https://rustup.rs">rustup ↗</a>, then build the current source with Cargo:</p><CopyCommand command={sourceInstall}/><p>The executable is installed into Cargo’s binary directory. Make sure that directory is on your PATH.</p><CopyCommand command="perfratio --help"/><p>Prebuilt artifacts, when available, are listed on the <a className="text-link" href={`${repository}/releases`}>release page ↗</a>. Package-manager commands for hyperfine install hyperfine; use perfratio’s own source or releases to get perfratio.</p></section>
<section id="first-run"><h2>Run your first comparison</h2><CopyCommand command="perfratio --warmup 3 'sleep 0.1' 'sleep 0.2'"/><p>Quote each command separately. Warmup runs execute before measurements. By default, perfratio performs at least 10 measurement runs and measures for at least 3 seconds.</p><CopyCommand command="perfratio --runs 20 './baseline' './optimized'"/><h3>Reduce environmental noise</h3><CopyCommand command="perfratio --check-system --schedule round-robin --warmup 3 './baseline' './optimized'"/><p>System checks report supported environmental diagnostics. Round-robin scheduling interleaves commands to distribute slow drift more fairly. Keep workloads, inputs and hardware conditions comparable.</p><p className="docs-note">Commands execute on your machine. Use commands and parameter values you trust; parameter substitution is verbatim, not shell-escaped. For very short commands, <code>--shell=none</code> avoids shell startup calibration noise and shell syntax.</p></section>
<section id="output"><h2>Read the output</h2><ul><li><strong>Time (mean ± σ)</strong>: average elapsed time and standard deviation across runs.</li><li><strong>User / System</strong>: CPU time spent in application code and in the kernel.</li><li><strong>Peak memory</strong>: process peak resident memory, distinct from total allocations.</li><li><strong>Relative speed</strong>: timing ratios between compared commands, with uncertainty.</li></ul><p>A ratio alone does not prove statistical significance. Look at variability, workload conditions and distributions.</p><CopyCommand command="perfratio --deep-stats './baseline' './optimized'"/><p>Deep statistics add bootstrapped 95% confidence intervals for mean and median, and two-sample hypothesis testing against reference commands with deterministic bootstrap resampling.</p><a className="text-link" href={`${repository}/blob/master/doc/understanding-output.md`}>Full output reference ↗</a></section>
<section id="energy"><h2>Measure energy and power</h2><CopyCommand command="perfratio --energy './benchmark'"/><p>Energy measurement requires supported, accessible hardware sensors. Linux RAPL reads counters from the powercap interface. Availability and permissions depend on the machine.</p><p>Energy is reported in Joules and average active power in Watts. Measurements cover the hardware domains exposed by the sensors; they are not an isolated measurement of only your process. Background work can influence the result.</p></section>
<section id="export"><h2>Export and share results</h2><CopyCommand command="perfratio --export results.json --export report.html './benchmark'"/><p>The file extension selects the export format. Use JSON for per-run analysis, CSV for tabular workflows, Markdown for documentation or HTML for a standalone report.</p><h3>Compare a saved baseline</h3><CopyCommand command="perfratio --export baseline.json './benchmark'"/><CopyCommand command="perfratio --compare baseline.json './benchmark'"/><p>Run the same workload after your change, keeping inputs and environment consistent. Read CLI help for additional comparison options.</p></section><h2>Keep exploring</h2><div className="actions"><a className="button primary" href={repository}>Source & full reference ↗</a><a className="button secondary" href={`${repository}/issues`}>Report an issue ↗</a></div></main></>;}
