'use client';
import {useState} from 'react';
import {CopyCommand} from './copy-command';
const examples=[
 {label:['Compare commands','Comparar comandos'],command:"perfratio --warmup 3 'grep -R TODO src' 'rg TODO src'",text:['Compare shell commands with warmup runs before measurement.','Compare comandos de shell com aquecimento antes da medição.']},
 {label:['Measure energy','Medir energia'],command:"perfratio --energy --deep-stats './baseline' './optimized'",text:['Measure Joules and average Watts on supported hardware. Linux RAPL uses accessible powercap sensors.','Meça Joules e Watts médios em hardware compatível. Linux RAPL usa sensores powercap acessíveis.']},
 {label:['Export results','Exportar resultados'],command:"perfratio --export results.json --export report.html './benchmark'",text:['Save results for analysis or generate a standalone HTML report.','Salve resultados para análise ou gere um relatório HTML independente.']},
 {label:['Reduce noise','Reduzir ruído'],command:"perfratio --check-system --schedule round-robin --warmup 3 './baseline' './optimized'",text:['Check the environment and interleave commands to reduce the effect of drift.','Verifique o ambiente e intercale comandos para reduzir o efeito de variações ao longo do tempo.']}
];
export function Examples({pt=false}:{pt?:boolean}){const [active,setActive]=useState(0);const lang=pt?1:0;return <div className="example-panel"><div role="tablist" aria-label={pt?'Exemplos de uso':'Usage examples'} className="tabs">{examples.map((e,i)=><button key={e.command} id={`tab-${i}`} role="tab" aria-selected={i===active} aria-controls={`panel-${i}`} tabIndex={i===active?0:-1} onClick={()=>setActive(i)} onKeyDown={event=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(event.key)){event.preventDefault();const n=event.key==='Home'?0:event.key==='End'?3:(active+(event.key==='ArrowRight'?1:3))%4;setActive(n);document.getElementById(`tab-${n}`)?.focus();}}}>{e.label[lang]}</button>)}</div><div className="example-content" role="tabpanel" id={`panel-${active}`} aria-labelledby={`tab-${active}`} tabIndex={0}><CopyCommand command={examples[active].command} pt={pt}/><p>{examples[active].text[lang]}</p></div></div>;}
