export function Hero({pt=false}:{pt?:boolean}) {
 const t=(en:string,br:string)=>pt?br:en;
 return <section className="hero"><div className="container">
  <div className="hero-kicker"><p className="eyebrow">{t('THE PERFORMANCE MEASUREMENT TOOLKIT','FERRAMENTAS PARA MEDIR DESEMPENHO')}</p><a href="https://better-web.org">{t('Joining Better Web','A caminho da Better Web')} ↗</a></div>
  <h1>{t('Every optimization','Toda otimização')}<br/>{t('has a','tem um')} <em>{t('trade-off.','custo.')}</em><span className="headline-period" aria-hidden="true">*</span></h1>
  <div className="hero-grid"><div className="hero-copy"><p className="hero-description">{t('A faster command. A smaller footprint. But at what cost? perfratio measures time, memory and energy, so you can see the whole picture.','Um comando mais rápido. Menos memória. Mas a que custo? perfratio mede tempo, memória e energia para você enxergar a visão completa.')}</p><div className="actions"><a className="button primary" href="#install">{t('Run your first benchmark','Faça seu primeiro benchmark')} <span aria-hidden="true">↗</span></a><a className="text-link" href="/docs/">{t('Read the field guide','Leia o guia de uso')} →</a></div><p className="hero-meta">RUST / Linux · macOS · Windows</p></div>
   <div className="measurement-board"><div className="board-heading"><span className="eyebrow">{t('EXPERIMENT 001','EXPERIMENTO 001')}</span><span className="board-status">{t('ILLUSTRATIVE DATA','DADOS ILUSTRATIVOS')}</span></div><div className="board-content"><div className="ratio-readout"><span className="ratio-label">{t('RELATIVE SPEED','VELOCIDADE RELATIVA')}</span><strong>1.60<span>×</span></strong><p>./optimized <span>{t('vs.','vs.')}</span> ./baseline</p><div className="ratio-ruler" aria-hidden="true"/><span className="ratio-footnote">{t('148.2 ms → 92.6 ms','148,2 ms → 92,6 ms')}</span></div><div className="board-metrics"><div className="measurement"><div><span>{t('ELAPSED TIME','TEMPO TOTAL')}</span><span>ms</span></div><div className="bar-pair"><div className="baseline-bar" style={{width:'100%'}}/><div className="optimized-bar" style={{width:'62.5%'}}/></div><p>148.2 <span>→</span> <strong>92.6</strong></p></div><div className="measurement"><div><span>{t('PEAK MEMORY','PICO DE MEMÓRIA')}</span><span>MB</span></div><div className="bar-pair"><div className="baseline-bar" style={{width:'100%'}}/><div className="optimized-bar" style={{width:'75.8%'}}/></div><p>24.0 <span>→</span> <strong>18.2</strong></p></div></div></div><div className="board-footer"><span><i className="legend-baseline"/>./baseline</span><span><i className="legend-optimized"/>./optimized</span><span>{t('Your workload. Your results.','Sua carga. Seus resultados.')}</span></div></div>
  </div><div className="hero-bottom"><p>{t('* Speed alone never tells the whole story.','* Velocidade sozinha nunca conta a história inteira.')}</p><a href="#features">{t('EXPLORE THE DIMENSIONS','EXPLORE AS DIMENSÕES')} <span aria-hidden="true">↓</span></a></div>
 </div></section>;
}
