import {Hero} from './hero';
import {repository,websiteRepository,sourceInstall} from './config';
import {CopyCommand} from './copy-command';
import {Examples} from './examples';
export function Landing({pt=false}:{pt?:boolean}){
 const t=(en:string,br:string)=>pt?br:en;
 const features=[
 ['01','TIME',t('Every run tells a story.','Cada execução conta uma história.'),t('Mean, median, standard deviation, user and system CPU time. Compare commands with relative performance ratios.','Média, mediana, desvio padrão e tempo de CPU de usuário e sistema. Compare comandos com razões de desempenho.')],
 ['02','MEMORY',t('See the memory footprint.','Entenda o uso de memória.'),t('Track peak resident memory alongside execution time. Understand the resource cost behind an optimization.','Acompanhe o pico de memória residente junto com o tempo de execução. Entenda o custo de recursos de uma otimização.')],
 ['03','ENERGY',t('Efficiency beyond speed.','Eficiência além da velocidade.'),t('Measure energy in Joules and average power in Watts with supported hardware sensors, including Linux RAPL.','Meça energia em Joules e potência média em Watts com sensores compatíveis, incluindo RAPL no Linux.')],
 ['04','STATISTICS',t('Put confidence in the result.','Tenha confiança no resultado.'),t('Bootstrap confidence intervals and two-sample significance tests with --deep-stats.','Intervalos de confiança por bootstrap e testes de significância com --deep-stats.')]
 ];
 return <><a className="skip" href="#main">{t('Skip to content','Ir para o conteúdo')}</a><header className="header"><div className="container header-inner"><a className="brand" href={pt?'/pt/':'/'}><span className="brand-mark" aria-hidden="true"><i/><i/><i/></span>perfratio<span className="brand-note">CLI</span></a><nav aria-label={t('Main navigation','Navegação principal')}><a href="#features">{t('Features','Recursos')}</a><a href="#examples">{t('Examples','Exemplos')}</a><a href="/docs/">{t('Docs','Documentação')}</a></nav><div className="header-actions"><a href={pt?'/':'/pt/'} lang={pt?'en':'pt-BR'} aria-label={pt?'Read in English':'Ler em português'}>{pt?'EN':'PT'}</a><a className="github-link" href={repository}>GitHub ↗</a></div></div></header><main id="main"><Hero pt={pt}/>
 <section id="features" className="section container"><div className="section-intro"><div><p className="eyebrow">01 / {t('THE WHOLE PICTURE','A VISÃO COMPLETA')}</p><h2>{t('Fast is only part','Velocidade é só parte')}<br/>{t('of the equation.','da equação.')}</h2></div><p>{t('A faster command is a good start. Knowing its resource cost and whether the difference is meaningful is a better benchmark.','Um comando mais rápido é um bom começo. Saber seu custo de recursos e se a diferença é significativa torna o benchmark melhor.')}</p></div><div className="features-grid">{features.map(([n,label,title,description])=><article className="feature" key={n}><div className="feature-top"><span>{n}</span><span>{label}</span></div><h3>{title}</h3><p>{description}</p></article>)}</div></section>
 <section className="workflow-section"><div className="container workflow"><div><p className="eyebrow">02 / {t('YOUR WORKFLOW','SEU FLUXO')}</p><h2>{t('Familiar commands.','Comandos familiares.')}<br/><span className="muted">{t('Deeper answers.','Respostas mais profundas.')}</span></h2><p>{t('Built on the heritage of hyperfine and joulex. Bring your existing shell commands and explore more of what happens when they run.','Construído sobre a herança de hyperfine e joulex. Use seus comandos de shell e explore mais do que acontece durante a execução.')}</p><a className="text-link" href="/docs/">{t('Explore the getting-started guide','Explorar o guia de primeiros passos')} →</a></div><ol className="workflow-list">{[
 [t('Prepare a fair comparison','Prepare uma comparação justa'),t('Warm up caches, check the system and interleave runs.','Aqueça caches, verifique o sistema e intercale execuções.')],
 [t('Measure what matters','Meça o que importa'),t('Compare runtime and memory. Add energy and deep statistics.','Compare tempo e memória. Adicione energia e estatística detalhada.')],
 [t('Take the evidence with you','Leve as evidências com você'),t('Export JSON, CSV, Markdown or a standalone HTML report.','Exporte JSON, CSV, Markdown ou um relatório HTML independente.')]
 ].map(([title,text],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></section>
 <section id="examples" className="section container"><p className="eyebrow">03 / {t('IN THE TERMINAL','NO TERMINAL')}</p><h2>{t('Your next benchmark','Seu próximo benchmark')}<br/>{t('starts here.','começa aqui.')}</h2><Examples pt={pt}/></section>
 <section id="install" className="install-section"><div className="container install-grid"><div><p className="eyebrow">04 / {t('GET STARTED','COMECE AQUI')}</p><h2>{t('Less setup.','Menos configuração.')}<br/><span className="accent">{t('More insight.','Mais clareza.')}</span></h2><p>{t('Install from the source repository with Cargo. Requires Rust 1.88 or newer.','Instale pelo repositório de código com Cargo. Requer Rust 1.88 ou mais recente.')}</p><a className="text-link" href={`${repository}/releases`}>{t('Explore releases','Ver releases')} ↗</a></div><div className="install-card"><span className="eyebrow">{t('BUILD FROM SOURCE','COMPILAR DO CÓDIGO')}</span><CopyCommand command={sourceInstall} pt={pt}/><div className="install-divider"/><span className="eyebrow">{t('RUN YOUR FIRST BENCHMARK','SEU PRIMEIRO BENCHMARK')}</span><CopyCommand command="perfratio --warmup 3 'sleep 0.1' 'sleep 0.2'" pt={pt}/><p>{t('Need help reading the results?','Precisa de ajuda para interpretar os resultados?')} <a href="/docs/#output">{t('Follow the guide →','Siga o guia →')}</a></p></div></div></section>
 <section className="section container community"><div><p className="eyebrow">{t('OPEN SOURCE. OPEN POSSIBILITIES.','CÓDIGO ABERTO. POSSIBILIDADES ABERTAS.')}</p><h2>{t('Better benchmarks.','Benchmarks melhores.')}<br/>{t('Built together.','Construídos juntos.')}</h2></div><div><p>{t('perfratio is moving into the Better Web ecosystem. Explore the code, report an issue or help shape what comes next.','perfratio está migrando para o ecossistema Better Web. Explore o código, reporte um problema ou ajude a construir os próximos passos.')}</p><div className="actions"><a className="button secondary" href={repository}>{t('Explore on GitHub','Explorar no GitHub')} ↗</a><a className="text-link" href="https://better-web.org">Better Web ↗</a></div></div></section></main><footer><div className="container footer-inner"><a className="brand" href={pt?'/pt/':'/'}>perfratio<span className="footer-tag">{t('Measure with confidence.','Meça com confiança.')}</span></a><div><a href="https://rustyll.better-web.org">Rustyll ↗</a><a href={websiteRepository}>{t('Website source','Código do site')} ↗</a><a href={`${repository}/blob/master/LICENSE-MIT`}>MIT / Apache-2.0</a></div></div></footer></>;
}
